meta_product_name: "BuzzerBet"
meta_title: "BuzzerBet | The bet app for NBA fans"
meta_description: "BuzzerBet is THE brand new betting application to share great moments with friend without wasting money, come and try it !"
meta_image: "lebron.jpg" # should exist in `app/assets/images/`
